USE [ChinaUnicom.Fuyang]
GO

/****** Object:  Table [dbo].[CM_CREDIT_EXCHANGE]    Script Date: 2014-11-10 21:47:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CM_CREDIT_EXCHANGE](
	[EXCHANGE_ID] [int] IDENTITY(10000,1) NOT NULL,
	[CHANNEL_GUID] [uniqueidentifier] NOT NULL,
	[EXCHANGE_CREDIT] [int] NOT NULL,
	[STATUS] [int] NULL,
	[EXCHANGE_DATETIME] [datetime] NULL,
	[EXCHANGE_USER] [int] NULL,
	[APPROVAL_DATETIME] [datetime] NULL,
	[APPROVAL_USER] [int] NULL,
	[FLAG] [int] NULL,
 CONSTRAINT [PK_CM_CREDIT_EXCHANGE] PRIMARY KEY CLUSTERED 
(
	[EXCHANGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
